// Initialization (this file was generated by my VM translator)
@256
D=A
@SP
M=D
@12
0;JMP

(CMP_TRUE)
@SP
A=M-1
M=-1
@R15
A=M
0;JMP

// push constant 17
@17
D=A
@SP
M=M+1
A=M-1
M=D
// push constant 17
@17
D=A
@SP
M=M+1
A=M-1
M=D
// eq
@CMP$ret0
D=A
@R15
M=D
@SP
AM=M-1
D=M
A=A-1
D=M-D
M=0
@CMP_TRUE
D;JEQ
(CMP$ret0)
// push constant 17
@17
D=A
@SP
M=M+1
A=M-1
M=D
// push constant 16
@16
D=A
@SP
M=M+1
A=M-1
M=D
// eq
@CMP$ret1
D=A
@R15
M=D
@SP
AM=M-1
D=M
A=A-1
D=M-D
M=0
@CMP_TRUE
D;JEQ
(CMP$ret1)
// push constant 16
@16
D=A
@SP
M=M+1
A=M-1
M=D
// push constant 17
@17
D=A
@SP
M=M+1
A=M-1
M=D
// eq
@CMP$ret2
D=A
@R15
M=D
@SP
AM=M-1
D=M
A=A-1
D=M-D
M=0
@CMP_TRUE
D;JEQ
(CMP$ret2)
// push constant 892
@892
D=A
@SP
M=M+1
A=M-1
M=D
// push constant 891
@891
D=A
@SP
M=M+1
A=M-1
M=D
// lt
@CMP$ret3
D=A
@R15
M=D
@SP
AM=M-1
D=M
A=A-1
D=M-D
M=0
@CMP_TRUE
D;JLT
(CMP$ret3)
// push constant 891
@891
D=A
@SP
M=M+1
A=M-1
M=D
// push constant 892
@892
D=A
@SP
M=M+1
A=M-1
M=D
// lt
@CMP$ret4
D=A
@R15
M=D
@SP
AM=M-1
D=M
A=A-1
D=M-D
M=0
@CMP_TRUE
D;JLT
(CMP$ret4)
// push constant 891
@891
D=A
@SP
M=M+1
A=M-1
M=D
// push constant 891
@891
D=A
@SP
M=M+1
A=M-1
M=D
// lt
@CMP$ret5
D=A
@R15
M=D
@SP
AM=M-1
D=M
A=A-1
D=M-D
M=0
@CMP_TRUE
D;JLT
(CMP$ret5)
// push constant 32767
@32767
D=A
@SP
M=M+1
A=M-1
M=D
// push constant 32766
@32766
D=A
@SP
M=M+1
A=M-1
M=D
// gt
@CMP$ret6
D=A
@R15
M=D
@SP
AM=M-1
D=M
A=A-1
D=M-D
M=0
@CMP_TRUE
D;JGT
(CMP$ret6)
// push constant 32766
@32766
D=A
@SP
M=M+1
A=M-1
M=D
// push constant 32767
@32767
D=A
@SP
M=M+1
A=M-1
M=D
// gt
@CMP$ret7
D=A
@R15
M=D
@SP
AM=M-1
D=M
A=A-1
D=M-D
M=0
@CMP_TRUE
D;JGT
(CMP$ret7)
// push constant 32766
@32766
D=A
@SP
M=M+1
A=M-1
M=D
// push constant 32766
@32766
D=A
@SP
M=M+1
A=M-1
M=D
// gt
@CMP$ret8
D=A
@R15
M=D
@SP
AM=M-1
D=M
A=A-1
D=M-D
M=0
@CMP_TRUE
D;JGT
(CMP$ret8)
// push constant 57
@57
D=A
@SP
M=M+1
A=M-1
M=D
// push constant 31
@31
D=A
@SP
M=M+1
A=M-1
M=D
// push constant 53
@53
D=A
@SP
M=M+1
A=M-1
M=D
// add
@SP
AM=M-1
D=M
A=A-1
M=M+D
// push constant 112
@112
D=A
@SP
M=M+1
A=M-1
M=D
// sub
@SP
AM=M-1
D=M
A=A-1
M=M-D
// neg
@SP
A=M-1
M=-M
// and
@SP
AM=M-1
D=M
A=A-1
M=M&D
// push constant 82
@82
D=A
@SP
M=M+1
A=M-1
M=D
// or
@SP
AM=M-1
D=M
A=A-1
M=M|D
// not
@SP
A=M-1
M=!M
