// Initialization (this file was generated by my VM translator)
@256
D=A
@SP
M=D

@12
0;JMP

(CMP_TRUE)
@SP
A=M-1
M=-1
@R15
A=M
0;JMP

// push constant 0
@0
D=A
@SP
M=M+1
A=M-1
M=D
// pop local 0         // sum = 0
@0
D=A
@1
A=M+D
D=A
@R15
M=D
@SP
AM=M-1
D=M
@R15
A=M
M=D
// label LOOP
(LOOP)
// push argument 0
@0
D=A
@2
A=M+D
D=M
@SP
M=M+1
A=M-1
M=D
// push local 0
@0
D=A
@1
A=M+D
D=M
@SP
M=M+1
A=M-1
M=D
// add
@SP
AM=M-1
D=M
A=A-1
M=M+D
// pop local 0	        // sum = sum + n
@0
D=A
@1
A=M+D
D=A
@R15
M=D
@SP
AM=M-1
D=M
@R15
A=M
M=D
// push argument 0
@0
D=A
@2
A=M+D
D=M
@SP
M=M+1
A=M-1
M=D
// push constant 1
@1
D=A
@SP
M=M+1
A=M-1
M=D
// sub
@SP
AM=M-1
D=M
A=A-1
M=M-D
// pop argument 0      // n--
@0
D=A
@2
A=M+D
D=A
@R15
M=D
@SP
AM=M-1
D=M
@R15
A=M
M=D
// push argument 0
@0
D=A
@2
A=M+D
D=M
@SP
M=M+1
A=M-1
M=D
// if-goto LOOP        // if n > 0, goto LOOP
@SP
AM=M-1
D=M
@LOOP
D;JNE
// push local 0        // else, pushes sum to the stack's top
@0
D=A
@1
A=M+D
D=M
@SP
M=M+1
A=M-1
M=D
// infinite loop end
(END)
@END
0;JMP
