// Initialization (this file was generated by the VM translator)
@256
D=A
@SP
M=D
@12
0;JMP

(CMP_TRUE)
@SP
A=M-1
M=-1
@R15
A=M
0;JMP

// push constant 10
@10
D=A
@SP
M=M+1
A=M-1
M=D
// pop local 0
@0
D=A
@1
A=M+D
D=A
@R15
M=D
@SP
AM=M-1
D=M
@R15
A=M
M=D
// push constant 21
@21
D=A
@SP
M=M+1
A=M-1
M=D
// push constant 22
@22
D=A
@SP
M=M+1
A=M-1
M=D
// pop argument 2
@2
D=A
@2
A=M+D
D=A
@R15
M=D
@SP
AM=M-1
D=M
@R15
A=M
M=D
// pop argument 1
@1
D=A
@2
A=M+D
D=A
@R15
M=D
@SP
AM=M-1
D=M
@R15
A=M
M=D
// push constant 36
@36
D=A
@SP
M=M+1
A=M-1
M=D
// pop this 6
@6
D=A
@3
A=M+D
D=A
@R15
M=D
@SP
AM=M-1
D=M
@R15
A=M
M=D
// push constant 42
@42
D=A
@SP
M=M+1
A=M-1
M=D
// push constant 45
@45
D=A
@SP
M=M+1
A=M-1
M=D
// pop that 5
@5
D=A
@4
A=M+D
D=A
@R15
M=D
@SP
AM=M-1
D=M
@R15
A=M
M=D
// pop that 2
@2
D=A
@4
A=M+D
D=A
@R15
M=D
@SP
AM=M-1
D=M
@R15
A=M
M=D
// push constant 510
@510
D=A
@SP
M=M+1
A=M-1
M=D
// pop temp 6
@6
D=A
@5
A=A+D
D=A
@R15
M=D
@SP
AM=M-1
D=M
@R15
A=M
M=D
// push local 0
@0
D=A
@1
A=M+D
D=M
@SP
M=M+1
A=M-1
M=D
// push that 5
@5
D=A
@4
A=M+D
D=M
@SP
M=M+1
A=M-1
M=D
// add
@SP
AM=M-1
D=M
A=A-1
M=M+D
// push argument 1
@1
D=A
@2
A=M+D
D=M
@SP
M=M+1
A=M-1
M=D
// sub
@SP
AM=M-1
D=M
A=A-1
M=M-D
// push this 6
@6
D=A
@3
A=M+D
D=M
@SP
M=M+1
A=M-1
M=D
// push this 6
@6
D=A
@3
A=M+D
D=M
@SP
M=M+1
A=M-1
M=D
// add
@SP
AM=M-1
D=M
A=A-1
M=M+D
// sub
@SP
AM=M-1
D=M
A=A-1
M=M-D
// push temp 6
@6
D=A
@5
A=A+D
D=M
@SP
M=M+1
A=M-1
M=D
// add
@SP
AM=M-1
D=M
A=A-1
M=M+D
// infinite loop end
(END)
@END
0;JMP
