// Initialization (this file was generated by the VM translator)
@256
D=A
@SP
M=D
@PROGRAM_START
0;JMP

(COMPARE_TRUE)
@SP
A=M-1
M=-1
@R15
A=M
0;JMP

(PROGRAM_START)
// push constant 111
@111
D=A
@SP
M=M+1
A=M-1
M=D
// push constant 333
@333
D=A
@SP
M=M+1
A=M-1
M=D
// push constant 888
@888
D=A
@SP
M=M+1
A=M-1
M=D
// pop static 8
@8
D=A
@16
A=M+D
D=A
@R15
M=D
@SP
AM=M-1
D=M
@R15
A=M
M=D
// pop static 3
@3
D=A
@16
A=M+D
D=A
@R15
M=D
@SP
AM=M-1
D=M
@R15
A=M
M=D
// pop static 1
@1
D=A
@16
A=M+D
D=A
@R15
M=D
@SP
AM=M-1
D=M
@R15
A=M
M=D
// push static 3
@3
D=A
@16
A=M+D
D=M
@SP
M=M+1
A=M-1
M=D
// push static 1
@1
D=A
@16
A=M+D
D=M
@SP
M=M+1
A=M-1
M=D
// sub
@SP
AM=M-1
D=M
A=A-1
M=M-D
// push static 8
@8
D=A
@16
A=M+D
D=M
@SP
M=M+1
A=M-1
M=D
// add
@SP
AM=M-1
D=M
A=A-1
M=M+D
// infinite loop end
(END)
@END
0;JMP
